# Generated by Django 3.0.7 on 2020-12-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('class_id', models.CharField(max_length=25)),
                ('creater_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Classroom',
            },
        ),
    ]
