# Generated by Django 3.0.7 on 2020-12-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name_plural': 'Members'},
        ),
    ]
